### ISSUE TITLE
FileNotFoundException in setUseLogFile

### ISSUE THREAD

**Issue by Notoh** [hugo4715/PluginLoader#3]
Running my fork of this, when calling setUseLogFile, a FileNotFoundException is thrown with the following stacktrace

~~~~
java.io.FileNotFoundException: logs\log.txt (Access is denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.PrintStream.<init>(Unknown Source)
        at fr.hugo4715.pluginloader.PluginManager.setUseLogFile(PluginManager.java:77)
~~~~

**Comment by Notoh** [comment]
Found a fix, not sure why but if you delete the logs folder prior to running the program, it will work.
